spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dms?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

mybatis-plus:
  mapper-locations: classpath:mapperxml/*
  type-aliases-package: cn.yesmylord.dms.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080